//import { useState } from "react"
import TextInput from "../components/TextInput";
import Header from "../components/Header"
export default function HomePage() {
    //const [loading, setLoading] = useState("");
    //const [result, setResult] = useState("");
    return (
        <div className="min-h-screen w-full bg-gray-50 dark:bg-gray-900">
            <Header />
            <div className="w-full max-w-3xl mx-auto px-4 sm:px-6 md:px-8 py-6 text-center">
                <h1 className="text-2xl sm:text-3xl md:text-4xl font-bold text-gray-800 dark:text-white mb-3">
                    AI Plagiarism Checker
                </h1>
                <p className="text-sm sm:text-base md:text-lg text-gray-600 dark:text-gray-300">
                    Paste or type your content below, then click "Analyze Text" to check 
                    the likelihood that your text was generated by AI. Highlighted sections 
                    will show areas that may be AI-generated.
                </p>
            </div>
            <div className="flex justify-center items-start pt-8 px-4 sm:px-6 md:px-8">
                <div className="w-full sm:w-4/5 md:w-3/5 lg:w-2/5">
                    <TextInput />
                </div>
            </div>
        </div>
        
    )
}