import { useContext } from "react";
import TextInput from "../components/TextInput";
import Header from "../components/Header";
import Spinner from "../components/Spinner";
import HomeAnalysisContext, { HomeAnalysisProvider } from "../contexts/HomeAnalysisProvider";

export default function HomePage() {
    return (
        <HomeAnalysisProvider>
            <HomePageContent />
        </HomeAnalysisProvider>
    );
}

function HomePageContent() {
    const { loading, result } = useContext(HomeAnalysisContext);

    return (
        <div className="min-h-screen w-full bg-gray-50 dark:bg-gray-900">
            <Header />
            <div className="w-full max-w-3xl mx-auto px-4 sm:px-6 md:px-8 py-4 text-center">
                <h1 className="text-2xl sm:text-3xl md:text-4xl font-bold dark:text-white mb-3">
                    AI Plagiarism Checker
                </h1>
                <p className="text-sm sm:text-base md:text-lg text-gray-600 dark:text-gray-300">
                    Paste or type your content below, then click "Analyze Text" to check 
                    the likelihood that your text was generated by AI. 
                    Sections highlighted in <span className="text-red-600 dark:text-red-400">red</span> are over 70% likely AI.  
                    Sections in <span className="text-yellow-600 dark:text-yellow-400">yellow</span> are around 40% likely AI.  
                    Sections in <span className="text-green-600 dark:text-green-400">green</span> are most likely human-written.
                </p>
            </div>
            <div className="flex justify-center items-start pt-4 px-4 sm:px-6 md:px-8">
                <div className="w-full sm:w-4/5 md:w-3/4">
                    <div className="w-full max-w-5xl mx-auto mb-4 border-4 border-[#9BAEC4]/10 rounded-lg bg-[#9BAEC4] dark:bg-gray-700 dark:border-gray-600">
                        <form>
                            <TextInput/>
                        </form>
                    </div>
                    {loading && <Spinner />}    
                </div>
            </div>

            {!loading && result && (
            <div className="max-w-5xl mx-auto px-4 sm:px-6 md:px-8 py-8">
                <h2 className="text-xl font-bold dark:text-white">
                    {result.headline}
                </h2>
                <h1 className="text-lg dark:text-gray-300 mb-4">
                    {result.percentageAi}% probability of being AI-generated
                </h1>
                <div className="text-left break-words">
                    {result.sentences.map((sentence, idx) => (
                    <span
                        key={idx}
                        className={`dark:text-white ${
                            sentence.prob > 0.7
                                ? "bg-green-200 dark:bg-red-700"
                                : sentence.prob > 0.4
                                ? "bg-yellow-200 dark:bg-yellow-700"
                                : "bg-red-200 dark:bg-green-700"
                        }`}
                    >
                        {sentence.text + " "}
                    </span>
                    ))}
                </div>
            </div>
        )}
        </div>   
    )
}